apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-build
  namespace: marc
spec:
  inputs:
    resources:
    - name: source
      targetPath: /
      type: git
  outputs:
    resources:
    - name: source
      type: git
  steps:
  - name: build
    image: gradle:5.4.1
    command:
    #- /usr/bin/gradle 
    - ./gradlew
    args:
    - bootRun
    volumeMounts:
        - name: marcvol
          mountPath: /workspace
          
          
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: marcTaskRun
  namespace: marc
spec:
  taskRef:
    name: mvn-build
  podTemplate:
    securityContext:
      runAsNonRoot: true
    volumes:
    - name: marcvol
      persistentVolumeClaim:
        claimName: marc
    
    
#https://github.com/jenkins-x/jx/issues/3767:
#- name: copy
#  image: busybox
#  command: mkdir
#  args:
#  - -p
#  - /workspace/go/src/github.com/jenkins-x/exposecontroller
#  - "&&"
#  - cp
#  - -R
#  - "./"

