apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-build
spec:
  inputs:
    resources:
    - name: source
      targetPath: /
      type: git
  outputs:
    resources:
    - name: source
      type: git
  steps:
  - name: build
    image: gradle
    command:
    - /usr/bin/gradle
    args:
    - bootJar
