apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn-build
spec:
  inputs:
    resources:
    - name: source
      targetPath: /
      type: git
  outputs:
    resources:
    - name: source
      type: git
  steps:
  - name: build
    image: gradle:5.4.1
    command:
    #- /usr/bin/gradle 
    - ./gradlew
    args:
    - bootRun
    
    
#https://github.com/jenkins-x/jx/issues/3767:
#- name: copy
#  image: busybox
#  command: mkdir
#  args:
#  - -p
#  - /workspace/go/src/github.com/jenkins-x/exposecontroller
#  - "&&"
#  - cp
#  - -R
#  - "./"

