---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: mapit-build-pipelinerun-
spec:
  serviceAccount: pipeline
  pipelineRef:
    name: build-pipeline
  resources:
  - name: app-git
    resourceRef:
      name: mapit-git
  - name: app-image
    resourceRef:
      name: mapit-image
